### ISSUE TITLE
Path to user directory wrong when working from other partition

### ISSUE THREAD

**Issue by ComFreek** [noflo/noflo-nodejs#12]
OS: Windows 8.1 Pro 64-bit
System partition: `C`
"Working partition" (from where the commands below will be executed): `P``

```
PS P:\noflo-nodejs\node_modules\.bin> ./noflo-nodejs-init.cmd --user [key] --host [host] --port
 [port] --label "Local NoFlo Test"

fs.js:439
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory 'P:\Users\ComFreek\.flowhub.json'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.writeFileSync (fs.js:978:15)
    at Object.exports.saveDefaults (P:\noflo-nodejs\node_modules\noflo-nodejs\index.js:30:6)
    at Object.<anonymous> (P:\noflo-nodejs\node_modules\noflo-nodejs\bin\noflo-nodejs-init:23:7)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
```
Everything works fine after running `mkdir P:\Users\ComFreek`.

**Comment by ensonic** [comment]
It is coming from 
https://github.com/noflo/noflo-nodejs/blob/master/index.js#L11-13
would be nice to know what those env-vars are set to under windows, but writing should not be fatal if those dirs don't exist. Will send a patch.
