### ISSUE TITLE
./node_modules/.bin/noflo-nodejs error after initial setup

### ISSUE THREAD

**Issue by gabalicious** [noflo/noflo-nodejs#169]
I followed README.md but I get the error below after running `./node_modules/.bin/noflo-nodejs`

```bash
Cannot read property '0' of undefined
    at /Users/justingaba/Development/noflo/node_modules/fbp-manifest/src/runtimes/noflo.js:185:22
    at tryCatcher (/Users/justingaba/Development/noflo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/justingaba/Development/noflo/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/Users/justingaba/Development/noflo/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/Users/justingaba/Development/noflo/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/Users/justingaba/Development/noflo/node_modules/bluebird/js/release/promise.js:699:18)
    at Promise._fulfill (/Users/justingaba/Development/noflo/node_modules/bluebird/js/release/promise.js:643:18)
    at Promise._resolveCallback (/Users/justingaba/Development/noflo/node_modules/bluebird/js/release/promise.js:459:14)
    ...
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ noflo: `noflo-nodejs .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ noflo script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/justingaba/.npm/_logs/2019-08-25T05_54_56_290Z-debug.log
```

**Comment by gabalicious** [comment]
logs
```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/justingaba/.nvm/versions/node/v10.16.3/bin/node',
1 verbose cli   '/Users/justingaba/.nvm/versions/node/v10.16.3/bin/npm',
1 verbose cli   'run',
1 verbose cli   'noflo' ]
2 info using npm@6.9.0
3 info using node@v10.16.3
4 verbose run-script [ 'prenoflo', 'noflo', 'postnoflo' ]
5 info lifecycle @~prenoflo: @
6 info lifecycle @~noflo: @
7 verbose lifecycle @~noflo: unsafe-perm in lifecycle true
8 verbose lifecycle @~noflo: PATH: /Users/justingaba/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/justingaba/Development/noflo/node_modules/.bin:/usr/local/sbin:/Users/justingaba/.nvm/versions/node/v10.16.3/bin:/Users/justingaba/bin:/usr/local/bin:/usr/local/sbin:/Users/justingaba/.nvm/versions/node/v10.16.3/bin:/Users/justingaba/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Library/Apple/bin
9 verbose lifecycle @~noflo: CWD: /Users/justingaba/Development/noflo
10 silly lifecycle @~noflo: Args: [ '-c', 'noflo-nodejs .' ]
11 silly lifecycle @~noflo: Returned: code: 1  signal: null
12 info lifecycle @~noflo: Failed to exec noflo script
13 verbose stack Error: @ noflo: `noflo-nodejs .`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/justingaba/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/Users/justingaba/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid @
15 verbose cwd /Users/justingaba/Development/noflo
16 verbose Darwin 19.0.0
17 verbose argv "/Users/justingaba/.nvm/versions/node/v10.16.3/bin/node" "/Users/justingaba/.nvm/versions/node/v10.16.3/bin/npm" "run" "noflo"
18 verbose node v10.16.3
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error @ noflo: `noflo-nodejs .`
22 error Exit status 1
23 error Failed at the @ noflo script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by gabalicious** [comment]
No longer having the issue. I think i installed with yarn the first time.

**Comment by aarmour** [comment]
I ran into this as well. For me, it was because my project's `package.json` did not have the `name` property.
