### ISSUE TITLE
fbpGraph.graph.loadFile is not a function

### ISSUE THREAD

**Issue by linonetwo** [noflo/noflo-nodejs#417]
From doc https://noflojs.org/documentation

```fbp
# In the graph we first need to define the nodes and the connections between them
Read(filesystem/ReadFile) OUT -> IN Display(core/Output)

# Start off the graph by sending a filename to the file reader
'package.json' -> IN Read
```

```
$ ./node_modules/.bin/noflo-nodejs --graph scripts/ShowContents.fbp --batch
```

![图片](https://github.com/noflo/noflo-nodejs/assets/3746270/e9750fe9-7eee-4777-b849-c76e6ad75efb)

```
PS E:\repo\TiddlyGit-Desktop> ./node_modules/.bin/noflo-nodejs --graph scripts/ShowContents.fbp --batch
fbpGraph.graph.loadFile is not a function
TypeError: fbpGraph.graph.loadFile is not a function
    at exports.loadGraph (E:\repo\TiddlyGit-Desktop\node_modules\.pnpm\noflo-nodejs@0.15.2\node_modules\noflo-nodejs\src\runtime.js:16:25)
    at exports.startGraph (E:\repo\TiddlyGit-Desktop\node_modules\.pnpm\noflo-nodejs@0.15.2\node_modules\noflo-nodejs\src\runtime.js:20:4)
    at E:\repo\TiddlyGit-Desktop\node_modules\.pnpm\noflo-nodejs@0.15.2\node_modules\noflo-nodejs\src\noflo-nodejs.js:11:29
```

Try add console.log there

```js
fbpGraph.graph {
  Graph: [class Graph extends EventEmitter],
  createGraph: [Function: createGraph],
  loadJSON: [Function: loadJSON],
  loadFBP: [Function: loadFBP],
  loadFile: undefined,
  equivalent: [Function: equivalent],
  mergeResolveTheirs: [Function: mergeResolveTheirsNaive]        
}
```

**Comment by linonetwo** [comment]
Sorry, I delete it manually in https://github.com/flowbased/fbp-graph/issues/375 and pnpm will reuse it across whole PC.
